export const COURSE_LIST_REQUEST = 'COURSE_LIST_REQUEST'; 
export const COURSE_LIST_SUCCESS = 'COURSE_LIST_SUCCESS';
export const COURSE_LIST_FAIL = 'COURSE_LIST_FAIL';

export const COURSE_PURCHASED_LIST_REQUEST = 'COURSE_PURCHASED_LIST_REQUEST'; 
export const COURSE_PURCHASED_LIST_SUCCESS = 'COURSE_PURCHASED_LIST_SUCCESS';
export const COURSE_PURCHASED_LIST_FAIL = 'COURSE_PURCHASED_LIST_FAIL';

export const COURSE_DETAILS_REQUEST = 'COURSE_DETAILS_REQUEST'; 
export const COURSE_DETAILS_SUCCESS = 'COURSE_DETAILS_SUCCESS';
export const COURSE_DETAILS_FAIL = 'COURSE_DETAILS_FAIL';

export const COURSE_CREATE_REQUEST = 'COURSE_CREATE_REQUEST'; 
export const COURSE_CREATE_SUCCESS = 'COURSE_CREATE_SUCCESS';
export const COURSE_CREATE_FAIL = 'COURSE_CREATE_FAIL';

export const COURSE_UPDATE_REQUEST = 'COURSE_CREATE_REQUEST'; 
export const COURSE_UPDATE_SUCCESS = 'COURSE_CREATE_SUCCESS';
export const COURSE_UPDATE_FAIL = 'COURSE_CREATE_FAIL';